apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-subscriptions
  description: Storefront app responsible to render buyer subscriptions data
  tags:
    - typescript
    - react
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex/my-subscriptions
    vtex.com/platform-flow-id: ""
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: CVB632FW
spec:
  system: orders
  lifecycle: stable
  owner: te-0020
  type: frontend-ui
  dependsOn: []
