const { checks } = require('./danger-rules.js')

checks.showFileChanges()
checks.checkChangelog()
checks.checkDescription()
checks.checkWIP()
checks.checkAssigneeAndReviewers()
checks.checkPRSize()
checks.checkTestFiles()
checks.checkLockFileUpdated()
checks.checkConsoleLog()
checks.checkMergeability()
