mutation RemoveSubscriptionFromGroup(
  $subscriptionsGroupId: String!
  $subscriptionId: String!
) {
  removeSubscription(
    subscriptionsGroupId: $subscriptionsGroupId
    subscriptionId: $subscriptionId
  ) @context(provider: "vtex.my-subscriptions-graphql") {
    cacheId
    orderGroup
    status
    totals {
      id
      value
    }
    totalValue
    subscriptions {
      subscriptionId
      sku {
        skuId
        name
        productName
        imageUrl
        detailUrl
        nameComplete
      }
      quantity
      priceAtSubscriptionDate
    }
    purchaseSettings {
      currencySymbol
    }
  }
}
