mutation UpdateSubscriptions(
  $subscriptionsGroupId: String!
  $subscriptions: [SubscriptionInput]!
) {
  updateSubscriptions(
    subscriptionsGroupId: $subscriptionsGroupId
    subscriptions: $subscriptions
  ) @context(provider: "vtex.my-subscriptions-graphql") {
    cacheId
    orderGroup
    status
    subscriptions {
      subscriptionId
      sku {
        skuId
        name
        productName
        imageUrl
        detailUrl
        nameComplete
      }
      quantity
      priceAtSubscriptionDate
    }
    purchaseSettings {
      currencySymbol
    }
  }
}
