query Addresses {
  profile @context(provider: "vtex.store-graphql") {
    cacheId
    addresses: address {
      id
      addressType
      addressName
      city
      complement
      country
      neighborhood
      number
      postalCode
      geoCoordinates
      receiverName
      reference
      state
      street
    }
  }
}
