query FrequencyOptions($subscriptionId: ID!) {
  frequencies: frequencyOptions(subscriptionId: $subscriptionId)
    @context(provider: "vtex.subscriptions-graphql") {
    periodicity
    interval
  }
}
