query CustomerListBy($value: String!, $option: GroupOption!) {
  list: customerListByOption(value: $value, option: $option, status: [ACTIVE]) {
    id
    name
    status
    items {
      sku {
        name
        imageUrl
        detailUrl
      }
    }
    plan {
      frequency {
        periodicity
        interval
      }
      purchaseDay
    }
  }
}
