query PaymentMethods {
  methods: customerPaymentMethods
    @context(provider: "vtex.subscriptions-graphql") {
    paymentSystemId
    paymentSystemName
    paymentSystemGroup
    paymentAccount {
      id
      cardNumber
    }
  }
}
