query SearchSubscribableProducts($searchTerm: String!) {
  search(searchTerm: $searchTerm)
    @context(provider: "vtex.subscriptions-graphql") {
    skuId
    name
    imageUrl
    price
    unitMultiplier
    measurementUnit
    brand
    plans
  }
}
