query Subscription($id: ID!) {
  subscription(id: $id)
    @context(provider: "vtex.subscriptions-graphql", scope: PRIVATE) {
    id
    cacheId
    status
    name
    isSkipped
    items {
      id
      quantity
      sku {
        id
        imageUrl
        name
        detailUrl
        productName
        variations
        measurementUnit
      }
      currentPrice
    }
    plan {
      frequency {
        periodicity
        interval
      }
      purchaseDay
    }
    nextPurchaseDate
    estimatedDeliveryDate
    purchaseSettings {
      currencyCode
      paymentMethod {
        paymentSystemId
        paymentSystemName
        paymentSystemGroup
        paymentAccount {
          id
          cardNumber
        }
      }
    }
    lastExecution {
      id
      status
    }
    totals {
      id
      value
    }
    shippingAddress {
      id
      street
      number
      complement
      neighborhood
      city
      state
      country
      postalCode
      reference
      geoCoordinate
      receiverName
      addressType
    }
  }
  addressId
  paymentAccountId
}
