query SubscriptionOrders($subscriptionId: ID!, $page: Int, $perPage: Int) {
  orders: subscriptionOrdersByGroup(
    subscriptionsGroupId: $subscriptionId
    page: $page
    perPage: $perPage
  ) @context(provider: "vtex.subscriptions-graphql") {
    list {
      ... on SubscriptionOrder {
        id
        status
        date
      }
    }
    totalCount
  }
}
