query Subscriptions($filter: [SubscriptionStatus]) {
  list: customerSubscriptionsGroupList(statusList: $filter)
    @context(provider: "vtex.subscriptions-graphql") {
    id
    cacheId
    status
    name
    nextPurchaseDate
    lastUpdate
    subscriptions {
      sku {
        imageUrl
        name
        detailUrl
        productName
      }
    }
    plan {
      frequency {
        periodicity
        interval
      }
      purchaseDay
    }
  }
}
