query PaymentMethods {
  methods: userPaymentMethods
    @context(provider: "vtex.my-subscriptions-graphql") {
    paymentSystem
    paymentAccount {
      accountId
      paymentSystem
      paymentSystemName
      cardNumber
      bin
    }
    paymentSystemName
    paymentSystemGroup
  }
}
