query SearchSubscribableProducts(
  $searchTerm: String!
  $page: Int
  $perPage: Int
) {
  searchProducts(
    searchTerm: $searchTerm
    perPage: $perPage
    page: $page
    subscribable: true
  ) @context(provider: "vtex.subscriptions-graphql") {
    list {
      ... on SearchProduct {
        unitMultiplier
        measurementUnit
        brand
        items {
          name
          skuId
          price
          imageUrl
          plans
        }
      }
    }
    totalCount
  }
}
