query Executions($subscriptionId: ID!, $page: Int, $perPage: Int) {
  executions: executionsBySubscription(
    subscriptionId: $subscriptionId
    page: $page
    perPage: $perPage
  ) @context(provider: "vtex.subscriptions-graphql") {
    list {
      ... on SubscriptionExecution {
        id
        status
        date
        order {
          orderId
          status
          packageAttachment {
            packages {
              trackingUrl
            }
          }
          shippingData {
            logisticsInfo {
              shippingEstimateDate
            }
          }
          paymentData {
            transactions {
              payments {
                url
              }
            }
          }
        }
      }
    }
    totalCount
  }
}
