query CustomerPaymentMethods {
  methods: customerPaymentMethods
    @context(provider: "vtex.subscriptions-graphql", scope: PRIVATE) {
    paymentSystemId
    paymentSystemName
    paymentSystemGroup
    paymentAccount {
      id
      cardNumber
    }
  }
}
