query FrequencyOptions($subscriptionsGroupId: ID!) {
  frequencies: frequencyOptions(subscriptionsGroupId: $subscriptionsGroupId)
    @context(provider: "vtex.subscriptions-graphql") {
    periodicity
    interval
  }
}
