query GetAddresses($orderGroup: String!) {
  addresses(orderGroup: $orderGroup)
    @context(provider: "vtex.my-subscriptions-graphql") {
    addressId
    street
    neighborhood
    number
    postalCode
    city
    state
    country
    reference
    complement
  }
}
