query GetAddresses($orderGroup: String!) {
  addresses(orderGroup: $orderGroup) {
    addressId
    street
    neighborhood
    number
    postalCode
    city
    state
    country
    reference
    complement
  }
}
