query GroupedSubscription($orderGroup: String, $customerId: String) {
  groupedSubscription(orderGroup: $orderGroup, customerId: $customerId) {
    cacheId
    orderGroup
    customerId
    plan {
      validity {
        end
        begin
      }
      type
      frequency {
        periodicity
        interval
      }
    }
    isSkipped
    purchaseSettings {
      purchaseDay
      seller
      salesChannel
      currencySymbol
      paymentMethod {
        paymentSystem
        paymentSystemName
        paymentSystemGroup
        paymentAccount {
          cardNumber
          accountId
        }
      }
    }
    items {
      id
      quantity
      status
      SubscriptionId
      sku {
        id
        name
        productName
        priceAtSubscriptionDate
        imageUrl
        detailUrl
      }
    }
    shippingAddress {
      addressId
      city
      receiverName
      reference
      street
      number
      neighborhood
      state
      country
    }
    customerProfile {
      email
      name
      phone
    }
    nextPurchaseDate
    totals {
      id
      value
    }
    totalValue
    purchaseSettings {
      purchaseDay
      seller
      salesChannel
    }
    instances {
      id
      date
      workflowId
      orderInfo {
        orderId
        orderGroup
        paymentUrl
      }
      message
      status
      isInRetry
    }
  }
}
