query GetPaymentSystems($orderGroup: String!) {
  paymentSystems(orderGroup: $orderGroup)
    @context(provider: "vtex.my-subscriptions-graphql") {
    paymentSystem
    paymentSystemName
    paymentSystemGroup
    paymentAccount {
      accountId
      paymentSystem
      paymentSystemName
      cardNumber
      bin
    }
  }
}
