query GroupedSubscription($orderGroup: String!) {
  groupedSubscription(orderGroup: $orderGroup)
    @context(provider: "vtex.my-subscriptions-graphql") {
    cacheId
    orderGroup
    status
    isSkipped
    name
    subscriptions {
      quantity
      sku {
        skuId
        imageUrl
        name
        detailUrl
        productName
      }
    }
    plan {
      frequency {
        periodicity
        interval
      }
      validity {
        begin
        end
      }
      type
    }
    shippingAddress {
      addressId
      street
      number
      complement
      neighborhood
      city
      state
      country
      postalCode
      reference
      geoCoordinate
      receiverName
      addressType
    }
    purchaseSettings {
      purchaseDay
      paymentMethod {
        paymentSystem
        paymentSystemName
        paymentSystemGroup
        paymentAccount {
          accountId
          cardNumber
        }
      }
    }
    nextPurchaseDate
    totals {
      id
      value
    }
    totalValue
    lastInstance {
      status
      orderGroup
      date
      dataInstanceId
      workflowId
      customerName
      customerEmail
      message
      context {
        items {
          skuId
          name
          imageUrl
          quantity
          price
          isGift
        }
        plan {
          frequency {
            periodicity
            interval
          }
          validity {
            begin
            end
          }
          type
        }
        value
        paymentSystemName
      }
    }
    shippingEstimate {
      estimatedDeliveryDate
    }
  }
}
