query GroupedSubscriptionsItems($status: [SubscriptionStatusEnum]) {
  items: groupedSubscriptions(status: $status)
    @context(provider: "vtex.my-subscriptions-graphql") {
    cacheId
    orderGroup
    status
    name
    nextPurchaseDate
    lastStatusUpdate
    subscriptions {
      sku {
        imageUrl
        name
        detailUrl
        productName
      }
    }
    plan {
      frequency {
        periodicity
        interval
      }
    }
  }
}
