query GroupedSubscription($orderGroup: String!) {
  groupedSubscription(orderGroup: $orderGroup) {
    cacheId
    orderGroup
    status
    isSkipped
    name
    subscriptions {
      SubscriptionId
      sku {
        SkuId
        name
        productName
        imageUrl
        detailUrl
        nameComplete
      }
      quantity
      priceAtSubscriptionDate
      cycleCount
      status
      createdAt
      lastUpdate
      originalOrderId
      isSkipped
    }
    plan {
      frequency {
        periodicity
        interval
      }
      validity {
        begin
        end
      }
      type
    }
    shippingAddress {
      addressId
      street
      number
      complement
      neighborhood
      city
      state
      country
      postalCode
      reference
      formattedAddress
      additionalComponents
      geoCoordinate
      receiverName
      addressType
    }
    purchaseSettings {
      purchaseDay
      paymentMethod {
        paymentSystem
        paymentSystemName
        paymentSystemGroup
        paymentAccount {
          accountId
          cardNumber
          bin
        }
      }
      seller
      salesChannel
      currencySymbol
      cycleCount
    }
    nextPurchaseDate
    totals {
      id
      value
    }
    totalValue
    instances {
      status
      orderGroup
      date
      dataInstanceId
      workflowId
      customerName
      customerEmail
      message
      context {
        items {
          skuId
          name
          imageUrl
          quantity
          price
          isGift
        }
        plan {
          frequency {
            periodicity
            interval
          }
          validity {
            begin
            end
          }
          type
        }
        value
        paymentSystemName
      }
    }
    lastInstance {
      status
      orderGroup
      date
      dataInstanceId
      workflowId
      customerName
      customerEmail
      message
      context {
        items {
          skuId
          name
          imageUrl
          quantity
          price
          isGift
        }
        plan {
          frequency {
            periodicity
            interval
          }
          validity {
            begin
            end
          }
          type
        }
        value
        paymentSystemName
      }
    }
    shippingEstimate {
      estimatedDeliveryDate
    }
  }
}
