mutation removeItem($orderGroup: String!, $itemId: String!) {
  removeItem(orderGroup: $orderGroup, itemId: $itemId) {
    cacheId
    items {
      quantity
      status
      sku {
        id
        name
        productName
        priceAtSubscriptionDate
        imageUrl
        detailUrl
      }
    }
  }
}
