mutation Retry($subscriptionsGroupId: ID!, $subscriptionOrderId: ID!) {
  retrySubscriptionOrder(
    subscriptionsGroupId: $subscriptionsGroupId
    subscriptionOrderId: $subscriptionOrderId
  ) @context(provider: "vtex.subscriptions-graphql")
}
