query SubscriptionsInfo($orderGroup: String!) {
  subscriptionsInfo: groupedSubscription(orderGroup: $orderGroup) {
    cacheId
    subscriptions {
      SubscriptionId
      sku {
        SkuId
        name
        productName
        imageUrl
        detailUrl
        nameComplete
      }
      quantity
      priceAtSubscriptionDate
      cycleCount
      status
      createdAt
      lastUpdate
      originalOrderId
      isSkipped
    }
    purchaseSettings {
      currencySymbol
    }
  }
}
