query SubscriptionOrdersByGroup(
  $subscriptionsGroupId: ID!
  $page: Int
  $perPage: Int
) {
  orders: subscriptionOrdersByGroup(
    subscriptionsGroupId: $subscriptionsGroupId
    page: $page
    perPage: $perPage
  ) @context(provider: "vtex.subscriptions-graphql") {
    list {
      id
      status
      date
    }
    totalCount
  }
}
