mutation updateSettings(
  $orderGroup: String!
  $purchaseDay: String
  $periodicity: String
  $interval: String
) {
  updateSettings(
    orderGroup: $orderGroup
    purchaseDay: $purchaseDay
    periodicity: $periodicity
    interval: $interval
  ) {
    cacheId
    purchaseSettings {
      purchaseDay
    }
    plan {
      frequency {
        periodicity
        interval
      }
    }
    nextPurchaseDate
    shippingEstimate {
      estimatedDeliveryDate
    }
  }
}
