mutation updatePaymentMethod(
  $subscriptionsGroupId: ID!
  $paymentSystemId: ID!
  $accountId: ID
) {
  updatePaymentMethod(
    subscriptionsGroupId: $subscriptionsGroupId
    paymentSystemId: $paymentSystemId
    accountId: $accountId
  ) @context(provider: "vtex.subscriptions-graphql") {
    cacheId
    purchaseSettings {
      paymentMethod {
        paymentSystemId
        paymentSystemName
        paymentSystemGroup
        paymentAccount {
          id
          cardNumber
          bin
        }
      }
    }
  }
}
