mutation updateIsSkipped($orderGroup: String!, $isSkipped: Boolean!) {
  updateIsSkipped(orderGroup: $orderGroup, isSkipped: $isSkipped)
    @context(provider: "vtex.my-subscriptions-graphql") {
    cacheId
    isSkipped
  }
}
