mutation updateSettings(
  $subscriptionsGroupId: ID!
  $purchaseDay: String
  $periodicity: Periodicity!
  $interval: Int!
) {
  updateSettings(
    subscriptionsGroupId: $subscriptionsGroupId
    purchaseDay: $purchaseDay
    periodicity: $periodicity
    interval: $interval
  ) @context(provider: "vtex.subscriptions-graphql") {
    cacheId
    purchaseSettings {
      purchaseDay
    }
    plan {
      frequency {
        periodicity
        interval
      }
    }
    nextPurchaseDate
    shippingEstimate {
      estimatedDeliveryDate
    }
  }
}
