mutation UpdateAddress($subscriptionsGroupId: ID!, $addressId: ID!) {
  updateAddress(
    subscriptionsGroupId: $subscriptionsGroupId
    addressId: $addressId
  ) @context(provider: "vtex.subscriptions-graphql") {
    cacheId
    shippingAddress {
      id
      street
      number
      complement
      neighborhood
      city
      state
      country
      postalCode
      reference
      geoCoordinate
      receiverName
      addressType
    }
  }
}
