mutation updatePaymentMethod(
  $subscriptionsGroupId: ID!
  $paymentSystemId: ID!
  $paymentAccountId: ID
) {
  updatePaymentMethod(
    subscriptionsGroupId: $subscriptionsGroupId
    paymentSystemId: $paymentSystemId
    paymentAccountId: $paymentAccountId
  ) @context(provider: "vtex.subscriptions-graphql") {
    cacheId
    purchaseSettings {
      paymentMethod {
        paymentSystemId
        paymentSystemName
        paymentSystemGroup
        paymentAccount {
          id
          cardNumber
        }
      }
    }
  }
}
