mutation updateStatus(
  $subscriptionsGroupId: ID!
  $status: SubscriptionStatus!
) {
  updateStatus(subscriptionsGroupId: $subscriptionsGroupId, status: $status)
    @context(provider: "vtex.subscriptions-graphql") {
    cacheId
    status
  }
}
