mutation updateAddress($orderGroup: String!, $addressId: String!) {
  updateAddress(orderGroup: $orderGroup, addressId: $addressId)
    @context(provider: "vtex.my-subscriptions-graphql") {
    cacheId
    shippingAddress {
      addressId
      street
      number
      complement
      neighborhood
      city
      state
      country
      postalCode
      reference
      geoCoordinate
      receiverName
      addressType
    }
  }
}
